#!/usr/bin/env python

ZOE_VIN = ""
ZOE_ZE_USERNAME = ""
ZOE_ZE_PASSWORD = ""

KAMEREON_API_KEY = "YjkKtHmGfaceeuExUDKGxrLZGGvtVS0J"
GIGYA_API_KEY = "3_VgdkgtIRH3AdHvJm-cjV2ug2EFE0lxt0IJzMC4MFqZjFpn_GYFXVdNZ19L7wZX0N"
